name: StaffChat
main: com.battleasya.staffchat.StaffChat
version: ${version}
api-version: 1.14
author: Dennie
website: http://battleasya.com
description: Enables staff communication in-game with a designated chat channel.
softdepend: [PlaceholderAPI]
commands:
  sc:
    description: Send a message in staff chat.
  sct:
    description: Toggle on or off chat mode in staff chat.
  screload:
    description: Reload config.
permissions:
  staffchat.*:
    default: op
    children:
      staffchat.use: true
      staffchat.reload: true