# StaffChat-Simplified 1.0.3

# https://github.com/denniemok/Staff-Chat-Simplified

# Support coloring messages with HEX codes on 1.16+ versions
# e.g., "#c8a2c8%name%: #e69296%message%."

chat-message: "&8[&4Staff Chat&8] &f&l%name%&8: &e%message%"

toggle-enable: "&8[&4Staff Chat&8] &aChat Mode Enabled."
toggle-disable: "&8[&4Staff Chat&8] &cChat Mode Disabled."

no-permission: "&8(&4&l!&8) &6Unknown Command."

message-syntax: "&cSyntax: /sc <message>"
toggle-syntax: "&cSyntax: /sct"
reload-syntax: "&cSyntax: /screload"

reload-config: "&8[&4Staff Chat&8] &cConfig Reloaded."