name: StaffChat
main: com.battleasya.staffchat.StaffChat
version: 1.0.2
author: Dennie
website: http://battleasya.com
description: Staff Chat System
commands:
  sc:
    description: Send a message in staff chat.
  sct:
    description: Enable or disable staff chat mode.
  screload:
    description: Reload config.
permissions:
  staffchat.*:
    default: op
    children:
      staffchat.use: true
      staffchat.reload: true