name: StaffChat
main: com.battleasya.staffchat.StaffChat
version: 1.0.4
api-version: 1.14
author: Dennie
website: http://battleasya.com
description: Enables staff communication in-game with a designated chat channel.
softdepend: [PlaceholderAPI]
commands:
  sc:
    description: Send a message to staff chat.
  sct:
    description: Enable or disable staff chat mode.
  screload:
    description: Reload config.
permissions:
  staffchat.*:
    default: op
    children:
      staffchat.use: true
      staffchat.reload: true